// <auto-generated />
namespace Inventiv.Tools.Elastic2Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ResultAndDescriptionAddedToTransportHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResultAndDescriptionAddedToTransportHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201802181316520_ResultAndDescriptionAddedToTransportHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
